import Link from "next/link";
import Image from "next/image";

const Arrow = () => <span aria-hidden="true">↗</span>;


export default function Home() {
  return <main className="overflow-hidden">
    <section className="bg-[#f5f0e8] px-5 pb-10 pt-5 md:px-10 md:pt-7">
      <nav className="mx-auto flex max-w-[1320px] items-center justify-between border-b border-[#252420]/15 pb-5">
        <Link href="/" className="font-display text-[23px] font-semibold tracking-[-0.06em]">getmenu<span className="text-[#d7663f]">.</span></Link>
        <div className="hidden items-center gap-8 font-mono text-[10px] uppercase tracking-[0.18em] text-[#766f65] md:flex"><a href="#pilihan">Pilihan</a><a href="#cara-kerja">Cara kerja</a><a href="#harga">Harga</a></div>
        <a href="https://getstore.my.id" className="rounded-full bg-[#252420] px-5 py-3 font-mono text-[10px] uppercase tracking-[0.16em] text-[#f5f0e8] transition-transform hover:-translate-y-0.5">GetStore <Arrow /></a>
      </nav>
      <div className="mx-auto grid max-w-[1320px] gap-12 pb-16 pt-14 md:grid-cols-[.9fr_1.1fr] md:items-end md:gap-20 md:pb-24 md:pt-24">
        <div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-[#d7663f]">GetMenu by GetStore / untuk restoran</p><h1 className="mt-7 max-w-[690px] font-display text-[clamp(3.4rem,7vw,7rem)] font-medium leading-[.9] tracking-[-.08em]">Menu yang bikin orang <span className="text-[#d7663f]">ingin pesan.</span></h1><p className="mt-8 max-w-[430px] text-[17px] leading-7 text-[#766f65]">Satu halaman yang rapi untuk membantu pelanggan melihat menu, memilih pesanan, dan datang ke kasir dengan lebih siap.</p><div className="mt-9 flex flex-wrap items-center gap-5"><Link href="/demo" className="group inline-flex items-center gap-4 rounded-full bg-[#d7663f] px-6 py-4 font-mono text-[10px] uppercase tracking-[.16em] text-white transition-transform hover:-translate-y-1">Lihat demo <span className="transition-transform group-hover:translate-x-1"><Arrow /></span></Link><a href="#harga" className="font-mono text-[10px] uppercase tracking-[.16em] text-[#766f65] underline decoration-[#d7663f] underline-offset-8">Lihat harga</a></div></div>
        <div className="relative min-h-[390px] md:min-h-[520px]"><div className="absolute right-0 top-0 h-[88%] w-[76%] bg-[#314d3a] p-5 text-[#f5f0e8] md:p-8"><div className="flex items-center justify-between border-b border-[#f5f0e8]/20 pb-4 font-mono text-[9px] uppercase tracking-[.16em]"><span>Demo / Kedai Pagi</span><span>Buka 07—22</span></div><p className="mt-16 max-w-[360px] font-display text-[clamp(2.6rem,5vw,5rem)] leading-[.9] tracking-[-.07em]">Makan enak, tanpa <span className="text-[#d7a34e]">bingung.</span></p><div className="mt-14 grid grid-cols-2 gap-3"><div className="h-28 bg-[#d7a34e] p-3 text-[#252420]"><p className="font-mono text-[9px] uppercase">01 / Pagi</p><p className="mt-12 font-display text-xl">Nasi Campur</p></div><div className="h-28 bg-[#d7663f] p-3"><p className="font-mono text-[9px] uppercase">02 / Favorit</p><p className="mt-12 font-display text-xl">Kopi Susu</p></div></div></div><div className="absolute bottom-0 left-0 w-[48%] border border-[#f5f0e8] bg-[#252420] p-4 text-[#f5f0e8] shadow-[12px_12px_0_#d7663f] md:p-5"><p className="font-mono text-[9px] uppercase leading-4 tracking-[.16em] text-[#aaa49a]">Mulai dari</p><p className="mt-2 font-display text-4xl tracking-[-.07em]">Rp150K</p><p className="mt-2 text-xs text-[#aaa49a]">Untuk menu statis yang siap dibagikan.</p></div></div>
      </div>
      <div className="mx-auto flex max-w-[1320px] justify-between border-t border-[#252420]/15 pt-4 font-mono text-[9px] uppercase tracking-[.18em] text-[#9a9289]"><span>menu.getstore.my.id</span><span>Scroll untuk melihat <span className="text-[#d7663f]">↓</span></span></div>
    </section>

    <section className="bg-[#e4dfd7] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-[1320px] gap-10 md:grid-cols-[.65fr_1.35fr] md:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-[#d7663f]">02 / Materi yang bisa dipajang</p><h2 className="mt-6 max-w-[400px] font-display text-[clamp(2.8rem,5vw,5rem)] leading-[.9] tracking-[-.08em]">Menu kamu, <span className="text-[#d7663f]">siap dilihat.</span></h2><p className="mt-6 max-w-[360px] text-sm leading-6 text-[#766f65]">Contoh materi visual GetMenu: QR code di meja dan halaman menu yang terasa seperti bagian dari restoran kamu.</p></div><div className="md:justify-self-end md:max-w-[680px]"><Image src="/images/getmenu-instagram-graphic-id.png" alt="Materi Instagram GetMenu berbahasa Indonesia yang menampilkan QR code meja dan halaman menu di ponsel" width={1080} height={1350} className="h-auto w-full shadow-[12px_12px_0_#314d3a]" /></div></div></section>

    <section id="pilihan" className="bg-[#252420] px-5 py-24 text-[#f5f0e8] md:px-10 md:py-36"><div className="mx-auto max-w-[1320px]"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><p className="font-mono text-[10px] uppercase tracking-[.22em] text-[#d7663f]">03 / Dua cara mulai</p><p className="max-w-[250px] text-sm leading-6 text-[#aaa49a]">Pilih berdasarkan cara pelanggan kamu memesan hari ini.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><article className="border border-[#f5f0e8]/20 p-6 md:p-9"><div className="flex items-start justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#d7a34e]">Untuk operasional yang lebih lengkap</p><h2 className="mt-4 font-display text-4xl tracking-[-.07em]">Self Service</h2></div><div className="shrink-0 text-right"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[#aaa49a]">mulai dari</p><p className="mt-1 font-display text-5xl leading-none tracking-[-.08em] text-[#d7a34e]">Rp300K</p></div></div><p className="mt-8 max-w-md text-[#aaa49a]">Menu lengkap dengan pembayaran Midtrans dan database admin. Tim kamu bisa mengubah menu dan harga sendiri.</p><ul className="mt-8 space-y-3 border-t border-[#f5f0e8]/15 pt-5 text-sm text-[#d8d1c7]"><li>+ Pembayaran online via Midtrans</li><li>+ Admin untuk mengelola menu</li><li>+ QR code stylized untuk dicetak di setiap meja</li><li>+ Cocok untuk delivery dan pickup</li></ul></article><article className="relative bg-[#f5f0e8] p-6 text-[#252420] shadow-[10px_10px_0_#d7663f] md:p-9"><div className="flex items-start justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#d7663f]">Untuk pesan di kasir</p><h2 className="mt-4 font-display text-4xl tracking-[-.07em]">Static Menu</h2></div><div className="shrink-0 text-right"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[#766f65]">mulai dari</p><p className="mt-1 font-display text-5xl leading-none tracking-[-.08em] text-[#d7663f]">Rp150K</p></div></div><p className="mt-8 max-w-md text-[#766f65]">Menu tetap dengan cart sederhana. Pelanggan memilih, melihat ringkasan, lalu menunjukkan pesanan ke kasir.</p><ul className="mt-8 space-y-3 border-t border-[#252420]/15 pt-5 text-sm text-[#4d4942]"><li>+ Halaman menu yang cepat</li><li>+ Cart dan ringkasan pesanan</li><li>+ QR code stylized untuk dicetak di setiap meja</li><li>+ Tanpa biaya payment gateway</li></ul></article></div></div></section>

    <section id="cara-kerja" className="bg-[#e4dfd7] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1320px] gap-14 md:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-[#d7663f]">02 / Alur yang ringan</p><h2 className="mt-7 max-w-[430px] font-display text-[clamp(2.8rem,5vw,5.2rem)] leading-[.92] tracking-[-.075em]">Dari scan sampai <span className="text-[#d7663f]">siap pesan.</span></h2></div><div className="border-t border-[#252420]/20">{[["01","Buka menu","Pelanggan scan QR atau membuka link menu kamu."],["02","Pilih pesanan","Menu dan cart membantu mereka memutuskan lebih cepat."],["03","Tunjukkan ringkasan","Untuk Static Menu, ringkasan tinggal ditunjukkan ke kasir."]].map(([n,t,d]) => <div key={n} className="grid grid-cols-[48px_1fr] gap-5 border-b border-[#252420]/20 py-7 sm:grid-cols-[70px_1fr_1fr]"><span className="font-mono text-[10px] text-[#d7663f]">{n}</span><h3 className="font-display text-2xl tracking-[-.05em]">{t}</h3><p className="col-start-2 mt-2 text-sm leading-6 text-[#766f65] sm:col-start-auto sm:mt-0">{d}</p></div>)}</div></div></section>

    <section id="harga" className="bg-[#d7663f] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-[#252420]">03 / Siap dipakai</p><h2 className="mt-7 max-w-[680px] font-display text-[clamp(2.8rem,5vw,5.3rem)] leading-[.92] tracking-[-.075em]">Mulai dari menu yang <span className="text-[#f5f0e8]">paling masuk akal.</span></h2></div><div className="max-w-[320px]"><p className="text-sm leading-6 text-[#4d2920]">Butuh website lengkap untuk bisnis kamu? GetMenu dibuat oleh GetStore.</p><a href="https://getstore.my.id" className="mt-6 inline-flex rounded-full bg-[#252420] px-6 py-4 font-mono text-[10px] uppercase tracking-[.16em] text-[#f5f0e8] transition-transform hover:-translate-y-1">Ke GetStore <Arrow /></a></div></div></section>

    <footer className="bg-[#f5f0e8] px-5 py-8 md:px-10"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-3 border-t border-[#252420]/15 pt-5 font-mono text-[10px] uppercase tracking-[.14em] text-[#766f65] md:flex-row"><span>GetMenu by GetStore</span><a href="https://getstore.my.id">getstore.my.id ↗</a></div></footer>
  </main>;
}
